import { defineNuxtPlugin } from "#app";
import VueHighlightJS from 'vue3-highlightjs'
/**
 * Just uncomment the needed theme for the highlighter
 */
// import 'highlight.js/styles/a11y-dark.css'
// import 'highlight.js/styles/a11y-light.css'
import 'highlight.js/styles/agate.css'
// import 'highlight.js/styles/an-old-hope.css'
// import 'highlight.js/styles/androidstudio.css'
// import 'highlight.js/styles/arduino-light.css'
// import 'highlight.js/styles/arta.css'
// import 'highlight.js/styles/ascetic.css'
// import 'highlight.js/styles/atelier-cave-dark.css'
// import 'highlight.js/styles/atelier-cave-light.css'
// import 'highlight.js/styles/atelier-dune-dark.css'
// import 'highlight.js/styles/atelier-dune-light.css'
// import 'highlight.js/styles/atelier-estuary-dark.css'
// import 'highlight.js/styles/atelier-estuary-light.css'
// import 'highlight.js/styles/atelier-forest-dark.css'
// import 'highlight.js/styles/atelier-forest-light.css'
// import 'highlight.js/styles/atelier-heath-dark.css'
// import 'highlight.js/styles/atelier-heath-light.css'
// import 'highlight.js/styles/atelier-lakeside-dark.css'
// import 'highlight.js/styles/atelier-lakeside-light.css'
// import 'highlight.js/styles/atelier-plateau-dark.css'
// import 'highlight.js/styles/atelier-plateau-light.css'
// import 'highlight.js/styles/atelier-savanna-dark.css'
// import 'highlight.js/styles/atelier-savanna-light.css'
// import 'highlight.js/styles/atelier-seaside-dark.css'
// import 'highlight.js/styles/atelier-seaside-light.css'
// import 'highlight.js/styles/atelier-sulphurpool-dark.css'
// import 'highlight.js/styles/atelier-sulphurpool-light.css'
// import 'highlight.js/styles/atom-one-dark-reasonable.css'
// import 'highlight.js/styles/atom-one-dark.css'
// import 'highlight.js/styles/atom-one-light.css'
// import 'highlight.js/styles/brown-paper.css'
// import 'highlight.js/styles/brown-papersq.png'
// import 'highlight.js/styles/codepen-embed.css'
// import 'highlight.js/styles/color-brewer.css'
// import 'highlight.js/styles/darcula.css'
// import 'highlight.js/styles/dark.css'
// import 'highlight.js/styles/default.css'
// import 'highlight.js/styles/docco.css'
// import 'highlight.js/styles/dracula.css'
// import 'highlight.js/styles/far.css'
// import 'highlight.js/styles/foundation.css'
// import 'highlight.js/styles/github-gist.css'
// import 'highlight.js/styles/github.css'
// import 'highlight.js/styles/gml.css'
// import 'highlight.js/styles/googlecode.css'
// import 'highlight.js/styles/gradient-dark.css'
// import 'highlight.js/styles/gradient-light.css'
// import 'highlight.js/styles/grayscale.css'
// import 'highlight.js/styles/gruvbox-dark.css'
// import 'highlight.js/styles/gruvbox-light.css'
// import 'highlight.js/styles/hopscotch.css'
// import 'highlight.js/styles/hybrid.css'
// import 'highlight.js/styles/idea.css'
// import 'highlight.js/styles/ir-black.css'
// import 'highlight.js/styles/isbl-editor-dark.css'
// import 'highlight.js/styles/isbl-editor-light.css'
// import 'highlight.js/styles/kimbie.dark.css'
// import 'highlight.js/styles/kimbie.light.css'
// import 'highlight.js/styles/lightfair.css'
// import 'highlight.js/styles/lioshi.css'
// import 'highlight.js/styles/magula.css'
// import 'highlight.js/styles/mono-blue.css'
// import 'highlight.js/styles/monokai-sublime.css'
// import 'highlight.js/styles/monokai.css'
// import 'highlight.js/styles/night-owl.css'
// import 'highlight.js/styles/nnfx-dark.css'
// import 'highlight.js/styles/nnfx.css'
// import 'highlight.js/styles/nord.css'
// import 'highlight.js/styles/obsidian.css'
// import 'highlight.js/styles/ocean.css'
// import 'highlight.js/styles/paraiso-dark.css'
// import 'highlight.js/styles/paraiso-light.css'
// import 'highlight.js/styles/pojoaque.css'
// import 'highlight.js/styles/pojoaque.jpg'
// import 'highlight.js/styles/purebasic.css'
// import 'highlight.js/styles/qtcreator_dark.css'
// import 'highlight.js/styles/qtcreator_light.css'
// import 'highlight.js/styles/railscasts.css'
// import 'highlight.js/styles/rainbow.css'
// import 'highlight.js/styles/routeros.css'
// import 'highlight.js/styles/school-book.css'
// import 'highlight.js/styles/school-book.png'
// import 'highlight.js/styles/shades-of-purple.css'
// import 'highlight.js/styles/solarized-dark.css'
// import 'highlight.js/styles/solarized-light.css'
// import 'highlight.js/styles/srcery.css'
// import 'highlight.js/styles/stackoverflow-dark.css'
// import 'highlight.js/styles/stackoverflow-light.css'
// import 'highlight.js/styles/sunburst.css'
// import 'highlight.js/styles/tomorrow-night-blue.css'
// import 'highlight.js/styles/tomorrow-night-bright.css'
// import 'highlight.js/styles/tomorrow-night-eighties.css'
// import 'highlight.js/styles/tomorrow-night.css'
// import 'highlight.js/styles/tomorrow.css'
// import 'highlight.js/styles/vs.css'
// import 'highlight.js/styles/vs2015.css'
// import 'highlight.js/styles/xcode.css'
// import 'highlight.js/styles/xt256.css'
// import 'highlight.js/styles/zenburn.css'


export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(VueHighlightJS)
})